eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: 8001

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server